apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ k8s_name }}-daily-backup
  namespace: {{ k8s_namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  schedule: "0 7 2-31 * *" # At 07:00 on every day-of-month from 2 through 31.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curlimage
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            args:
              - --request
              - POST
              - --fail
              - {{ k8s_name }}-postgres-backup-tool:8080/db/backup?retention_period=1
          restartPolicy: Never