apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ k8s_name }}
  namespace: {{ k8s_namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
