apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ k8s_name }}
  namespace: {{ k8s_namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  # Default path on node: /var/lib/rancher/k3s/storage
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
