apiVersion: v1
kind: Secret
metadata:
  name: {{ k8s_name }}
  namespace: {{ k8s_namespace }}
stringData:
  username: {{ db_username }}
  password: {{ db_password }}
  exporterUsername: {{ exporter_username }}
  exporterPassword: {{ exporter_password }}
  initdb_sql: |-
    {{ init_db_sql | indent(4) }}
  grant_sql: |-
    {{ grant_sql | indent(4) }}