apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ k8s_name }}-weekly-cleanup
  namespace: {{ k8s_namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  schedule: "30 6 * * 0" # At 06:30 on Sunday.
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curlimage
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            args:
              - --request
              - POST
              - --fail
              - {{ k8s_name }}-postgres-backup-tool:8080/db/cleanup
          restartPolicy: Never