namespace: mucsi96
name: kubetools
version: 1.0.0
readme: README.md
authors:
- Igor Bari
manifest:
  directives:
    - include README.md LICENSE
    - recursive-include roles **
    - recursive-include plugins **
  omit_default_directives: true