- name: Create k8s namespace
  kubernetes.core.k8s:
    state: present
    kind: namespace
    name: "{{ k8s_namespace }}"
- name: Get checksums
  ansible.builtin.set_fact:
    secret_checksum: "{{ lookup('ansible.builtin.template', 'secret.yaml') | checksum }}"
- name: Add kubernetes resources
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) }}"
    wait: true
  with_items:
    - persistent_volume_claim.yaml
    - secret.yaml
    - deployment.yaml
    - service.yaml
    - service_monitor.yaml

