- name: Install dependencies for setting up apt sources
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: true

- name: Create the directory for keyrings
  become: true
  ansible.builtin.file:
    state: directory
    path: /etc/apt/keyrings
    mode: 0755

- name: Authorize Docker GPG key
  become: true
  ansible.builtin.apt_key:
    url: "{{ docker_apt_gpg_key }}"
    keyring: "{{ docker_apt_keyring }}"

- name: Add Docker apt repository to source list
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository }}"
    filename: "{{ docker_apt_filename }}"
    state: present
    update_cache: true

- name: Install docker and its dependecies
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  notify:
    - Start Docker service

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    group: docker
