- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - python3-pip
      - python3-debian
    update_cache: true

- name: Setup Docker repository
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/{{ ansible_distribution | lower }}
    suites: "{{ ansible_distribution_release }}"
    components: stable
    architectures: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
    signed_by: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

- name: Install docker and its dependecies
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  notify:
    - Start Docker service

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    group: docker
