- name: Install docker for APT
  ansible.builtin.import_tasks: install_docker_apt.yaml
  when: ansible_os_family == 'Debian'

- name: Install docker with DNF
  ansible.builtin.import_tasks: install_docker_dnf.yaml
  when: ansible_os_family == 'RedHat'

- name: Flush handlers
  meta: flush_handlers