- name: Install docker for Ubuntu
  ansible.builtin.import_tasks: install_docker_ubuntu.yaml
  when: ansible_distribution == 'Ubuntu'

- name: Install docker with DNF
  ansible.builtin.import_tasks: install_docker_dnf.yaml
  when: ansible_os_family == 'RedHat'

- name: Flush handlers
  meta: flush_handlers