- name: Deploy Postgres monitoring resources
  delegate_to: localhost
  kubernetes.core.k8s:
    definition: "{{ lookup('ansible.builtin.template', item) }}"
    wait: true
  with_items:
    - logs/grafana_dashboard.yaml
