- name: Deploy loki-stack
  delegate_to: localhost
  kubernetes.core.helm:
    kubeconfig: "{{ k8s_admin_config_path }}"
    name: loki-stack
    chart_repo_url: https://grafana.github.io/helm-charts
    chart_ref: loki-stack
    chart_version: "{{ loki_stack_chart_version }}"
    wait: true
    release_namespace: "{{ k8s_namespace }}"
    release_values:
      loki:
        isDefault: false
      
      grafana:
        sidecar:
          dashboards:
            enabled: true
          datasources:
            enabled: false
