- name: Deploy loki-stack
  kubernetes.core.helm:
    name: loki-stack
    chart_repo_url: https://grafana.github.io/helm-charts
    chart_ref: loki-stack
    chart_version: 2.8.9
    wait: true
    release_namespace: "{{ k8s_namespace }}"
    release_values:
      loki:
        isDefault: false
      
      grafana:
        sidecar:
          dashboards:
            enabled: true
          datasources:
            enabled: false
