- name: Load k3s config
  become: true
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: kube_config
- name: Parse k3s config
  ansible.builtin.set_fact:
    kube_config: "{{ kube_config.content | b64decode | from_yaml }}"

- name: Create remote kubernetes config folder
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: 0700
- name: Create remote kubernetes config
  ansible.builtin.copy:
    dest: ~/.kube/config
    content: "{{ lookup('ansible.builtin.template', 'kube_config.yml') }}"
    mode: 0600
  vars:
    certificate_authority_data: "{{ kube_config.clusters.0.cluster['certificate-authority-data'] }}"
    client_certificate_data: "{{ kube_config.users.0.user['client-certificate-data'] }}"
    client_key_data: "{{ kube_config.users.0.user['client-key-data'] }}"
    host: 127.0.0.1
