- name: Create longhorn-system namespace
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    kind: namespace
    name: longhorn-system

- name: Add kubernetes resources
  delegate_to: localhost
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_admin_config_path }}"
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) }}"
    wait: true
    wait_timeout: 300
  with_items:
    - longhorn.yaml

# - name: Install Longhorn Helm chart
#   delegate_to: localhost
#   kubernetes.core.helm:
#     kubeconfig: "{{ k8s_admin_config_path }}"
#     name: longhorn
#     chart_repo_url: https://charts.longhorn.io
#     chart_ref: longhorn
#     chart_version: "{{ longhorn_version }}"
#     wait: true
#     release_namespace: longhorn-system
#     release_values:
#       longhornUI:
#         replicas: 1
