- name: Install pip3
  become: true
  ansible.builtin.apt:
    name: python3-pip
    state: present
- name: Install kubernetes client
  ansible.builtin.pip:
    name:
      - kubernetes == {{ kubernetes_client_version }}
