- name: Check internet connection
  ansible.builtin.include_role:
    name: check_internet_connection

- name: Install Docker
  ansible.builtin.include_role:
    name: install_docker

- name: Disable swap
  ansible.builtin.include_role:
    name: disable_swap

- name: Install K3s
  ansible.builtin.import_tasks: install_k3s.yaml

- name: Install Helm
  ansible.builtin.import_tasks: install_helm.yaml

- name: Pull kubernetes admin config
  ansible.builtin.include_role:
    name: pull_kube_admin_config

- name: Create Ansible token
  ansible.builtin.import_tasks: create_token.yaml

- name: Pull kubernetes ansible config
  ansible.builtin.include_role:
    name: pull_kube_ansible_config

- name: Wait for the Traefik CRD to be created
  become: true
  ansible.builtin.command:
    cmd: /usr/local/bin/kubectl get crd/ingressroutes.traefik.containo.us
  register: crd
  changed_when: false
  until: crd.rc == 0
  delay: 3
  retries: 30

- name: Configure Traefik
  delegate_to: localhost
  kubernetes.core.k8s:
    kubeconfig: "{{ k8s_admin_config_path }}"
    state: present
    definition: "{{ lookup('ansible.builtin.template', 'traefik_config.yaml') }}"
    wait: true
