---
argument_specs:
  main:
    options:
      k8s_name:
        type: str
      k8s_namespace:
        type: str
        required: true
      app_port:
        type: str
      identity_provider_base_path:
        type: str
        required: true
      client_id:
        type: str
        required: true
      client_secret:
        type: str
        required: true
      host_prefix:
        type: str
        required: true
      base_path:
        type: str
