k3s_version: v1.28.3+k3s2 # https://github.com/k3s-io/k3s/releases
helm_version: v3.13.2 # https://github.com/helm/helm/releases
longhorn_version: 1.5.3 #https://artifacthub.io/packages/helm/longhorn/longhorn