- name: Setup NTP for Debian
  ansible.builtin.import_tasks: ntp_debian.yaml
  when: ansible_os_family == 'Debian'

- name: Setup NTP for RedHat
  ansible.builtin.import_tasks: ntp_redhat.yaml
  when: ansible_os_family == 'RedHat'