subdomain: kubetools
k8s_namespace: kubetools
auth_middelware_name: auth
auth_middelware_namespace: authelia
host_prefix: demo
hostname: "{{ subdomain }}.{{ public_domainname }}"
db_name: kubetools
db_host: postgres-db
db_port: 5432
db_username: "{{ lookup('ansible.builtin.password', '/dev/null length=12 chars=ascii_lowercase', seed='{{ inventory_hostname }}-db-username') }}"
db_password: "{{ lookup('ansible.builtin.password', '/dev/null length=20', seed='{{ inventory_hostname }}-db-password') }}"
webdriver_host: webdriver-chrome
webdriver_port: 4444
spring_admin_server_name: spring-boot-admin-server
spring_admin_server_namespace: monitoring
spring_admin_server_port: 9090
db_backup_bucket: kubetools-backups
db_backup_region: us-east-1
api_client_id: demo-app
api_client_secret: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits length=72', seed='{{ inventory_hostname }}-open-id-connect-demo-app-client-secret') }}"
open_id_connect_clients:
  - id: "{{ api_client_id }}"
    secret: "{{ api_client_secret }}"
    redirect_uris:
      - "https://{{ host_prefix }}.{{ hostname }}/signin-redirect-callback"

k8s_admin_config_path: "~/.kube/admin-config"
k8s_ansible_config_path: "~/.kube/ansible-config"
