subdomain: kubetools
k8s_namespace: kubetools
auth_middelware_name: auth
auth_middelware_namespace: authelia
hostname: "{{ subdomain }}.{{ public_domainname }}"
db_name: kubetools
db_host: postgres-db
db_port: 5432
db_username: "{{ lookup('ansible.builtin.password', '/dev/null length=12 chars=ascii_lowercase', seed='{{ inventory_hostname }}-db-username') }}"
db_password: "{{ lookup('ansible.builtin.password', '/dev/null length=20', seed='{{ inventory_hostname }}-db-password') }}"
spring_admin_server_name: spring-boot-admin-server
spring_admin_server_namespace: monitoring
spring_admin_server_port: 9090
db_backup_bucket: kubetools-backups
db_backup_region: us-east-1

k8s_admin_config_path: "~/.kube/admin-config"
k8s_ansible_config_path: "~/.kube/ansible-config"
k3s_version: v1.28.3+k3s2 # https://github.com/k3s-io/k3s/releases
helm_version: v3.13.2 # https://github.com/helm/helm/releases
