apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ k8s_name }}-spring-boot-admin
  namespace: {{ k8s_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ k8s_name }}-spring-boot-admin
  template:
    metadata:
      labels:
        app: {{ k8s_name }}-spring-boot-admin
    spec:
      containers:
      - name: {{ k8s_name }}-spring-boot-admin
        image: mucsi96/kubetools-spring-boot-admin:latest
        resources:
          requests:
            memory: 200Mi
            cpu: 200m
          limits:
            memory: 500Mi
            cpu: 400m
        ports:
        - name: http
          containerPort: 8099
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8099
          initialDelaySeconds: 15
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8099
          initialDelaySeconds: 15
          failureThreshold: 30
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]