apiVersion: v1
kind: Service
metadata:
  name: {{ spring_admin_server_name }}
  namespace: {{ k8s_namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ spring_admin_server_port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ k8s_name }}-spring-boot-admin