apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ k8s_name }}-route
  namespace: {{ k8s_namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: HostRegexp(`{{ host_prefix }}.{host:[a-z-.]+}`) && PathPrefix(`{{ base_path }}`)
      middlewares:
        - name: {{ auth_middelware_name }}
          namespace: {{ auth_middelware_namespace }}
        - name: {{ k8s_name }}-stripprefix
          namespace: {{ k8s_namespace }}
      services:
        - kind: Service
          name: {{ k8s_name }}
          namespace: {{ k8s_namespace }}
          port: http