apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ k8s_name }}
  namespace: {{ k8s_namespace }}
spec:
  endpoints:
    - port: actuator
      path: /actuator/prometheus
  selector:
    matchLabels:
      app: {{ k8s_name }}