apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-route
  namespace: {{ k8s_namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: HostRegexp(`longhorn.{host:[a-z0-9-.]+}`)
      middlewares:
        - name: {{ auth_middelware_name }}
          namespace: {{ auth_middelware_namespace }}
        - name: {{ k8s_name }}-authorization
          namespace: {{ k8s_namespace }}
      services:
        - kind: Service
          name: longhorn-frontend
          namespace: longhorn-system
          port: http