---
argument_specs:
  main:
    options:
      hostname:
        type: str
        required: true
      auth_middelware_name:
        type: str
        required: true
      auth_middelware_namespace:
        type: str
        required: true
      spring_admin_server_name:
        type: str
        required: true
      spring_admin_server_port:
        type: int
        required: false