apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ k8s_name }}
  namespace: {{ k8s_namespace }}
spec:
  endpoints:
    - port: metrics
      path: /metrics
  selector:
    matchLabels:
      app: {{ k8s_name }}