apiVersion: v1
kind: Config
clusters:
  - name: cluster
    cluster:
      server: {{ k8s_server }}
      certificate-authority-data: {{ k8s_ca_cert }}
      insecure-skip-tls-verify: false
users:
  - name: cluster
    user:
      client-certificate-data: {{ k8s_client_cert }}
      client-key-data: {{ k8s_client_key }}
contexts:
  - name: cluster
    context:
      cluster: cluster
      name: cluster
      user: cluster
preferences: {}
current-context: cluster
