alias ap='ansible-playbook'
alias ave='ansible-vault encrypt vars/vault.yaml'
alias avd='ansible-vault decrypt vars/vault.yaml'
alias avv='ansible-vault view vars/vault.yaml'
alias ct='cloudflared tunnel'
alias mt='mvn test'
alias mr='mvn spring-boot:run -P local'