---
argument_specs:
  main:
    options:
      k8s_name:
        type: str
      k8s_namespace:
        type: str
        required: true
      image:
        type: str
        required: true
      app_port:
        type: str
      app_env:
        type: dict
      host_prefix:
        type: str
        required: true
      base_path:
        type: str
