apiVersion: v1
kind: Service
metadata:
  name: {{ k8s_name }}
  namespace: {{ k8s_namespace }}
spec:
  ports:
    - name: http
      port: 9091
      protocol: TCP
      targetPort: {{ app_port }}
  selector:
    app: {{ k8s_name }}
