apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ k8s_name }}
  namespace: {{ k8s_namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ app_domain }}.{{ hostname }}`)
      services:
        - kind: Service
          name: {{ k8s_name }}
          port: http
