- name: Create k8s namespace
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    kind: namespace
    name: "{{ k8s_namespace }}"
- name: Get checksums
  ansible.builtin.set_fact:
    secret_checksum: "{{ lookup('ansible.builtin.template', 'secret.yaml') | checksum }}"
- name: Get latest image version
  ansible.builtin.include_role:
    name: get_latest_image_version
- name: Add kubernetes resources
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) }}"
    wait: true
    wait_timeout: 300
  with_items:
    - secret.yaml
    - deployment.yaml
    - service.yaml
    - route.yaml
