apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ k8s_name }}-prometheus-redirect
  namespace: {{ k8s_namespace }}
spec:
  redirectRegex:
    regex: https?://([a-z-.]+)/?$
    replacement: https://${1}/targets