apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-route
  namespace: {{ k8s_namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: HostRegexp(`prometheus.{host:[a-z0-9-.]+}`)
      middlewares:
        - name: {{ auth_middelware_name }}
          namespace: {{ auth_middelware_namespace }}
        - name: {{ k8s_name }}-authorization
          namespace: {{ k8s_namespace }}
        - name: {{ k8s_name }}-prometheus-redirect
          namespace: {{ k8s_namespace }}
      services:
        - kind: Service
          name: kube-prometheus-stack-prometheus
          namespace: {{ k8s_namespace }}
          port: http-web