- name: Create k8s namespace
  kubernetes.core.k8s:
    state: present
    kind: namespace
    name: "{{ k8s_namespace }}"
- name: Add deployment and service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) }}"
    wait: true
  with_items:
    - config-map.yaml
    - secret.yaml
    - deployment.yaml
