apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ k8s_name }}
  namespace: {{ k8s_namespace }}
spec:
  selector:
    matchLabels:
      app: {{ k8s_name }}
  template:
    metadata:
      labels:
        app: {{ k8s_name }}
    spec:
      containers:
        - name: {{ k8s_name }}
          image: seleniarm/standalone-chromium:117.0-chromedriver-117.0-grid-4.10.0-20230926
          resources:
            requests:
              memory: 800Mi
              cpu: 40m
            limits:
              memory: 1Gi
              cpu: 500m
          ports:
            - name: http
              containerPort: 4444
          livenessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /wd/hub/status
              port: 4444
            initialDelaySeconds: 10
            timeoutSeconds: 5
          terminationGracePeriodSeconds: 5
