management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
spring:
  jmx:
    enabled: true
springdoc:
  swagger-ui:
    path: /
kubetools:
  introspection-uri: /
  user-info-uri: /
  client-id: clientId
  client-secret: clientSecret