- name: Load k3s config
  ansible.builtin.slurp:
    src: ~/.kube/config
  register: kube_config_raw

- name: Parse k3s config
  ansible.builtin.set_fact:
    kube_config: "{{ kube_config_raw.content | b64decode | from_yaml }}"
    host: "{{ ansible_host }}"

- name: Create local kubernetes config folder
  ansible.builtin.file:
    path: "{{ local_kube_config | dirname }}"
    state: directory
    mode: 0700
  delegate_to: localhost

- name: Create local kubernetes config
  ansible.builtin.copy:
    dest: "{{ local_kube_config }}"
    content: "{{ lookup('ansible.builtin.template', 'kube_config.yml') }}"
    mode: 0600
  vars:
    certificate_authority_data: "{{ kube_config.clusters.0.cluster['certificate-authority-data'] }}"
    client_certificate_data: "{{ kube_config.users.0.user['client-certificate-data'] }}"
    client_key_data: "{{ kube_config.users.0.user['client-key-data'] }}"
  delegate_to: localhost
