apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ k8s_name }}-grafana-auth
  namespace: {{ k8s_namespace }}
spec:
  headers:
    customRequestHeaders:
      X-WEBAUTH-USER: admin