apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-route
  namespace: {{ k8s_namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ app_host }}`)
      middlewares:
        - name: {{ auth_middelware_name }}
          namespace: {{ auth_middelware_namespace }}
        - name: {{ k8s_name }}-grafana-auth
          namespace: {{ k8s_namespace }}
      services:
        - kind: Service
          name: kube-prometheus-stack-grafana
          namespace: {{ k8s_namespace }}
          port: http-web