---
argument_specs:
  main:
    options:
      cloudflare_cert:
        type: str
        required: true
      hostname:
        type: str
        required: true
      subdomain:
        type: str
        required: true
      tunnel_name:
        type: str
        required: true
