apiVersion: v1
kind: Secret
metadata:
  name: {{ k8s_name }}
  namespace: {{ k8s_namespace }}
stringData:
  credentials.json: >
    {
      "AccountTag": "{{ tunnel_credentials.AccountTag }}",
      "TunnelSecret": "{{ tunnel_credentials.TunnelSecret }}",
      "TunnelID": "{{ tunnel_credentials.TunnelID }}"
    }