apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ansible
subjects:
- kind: ServiceAccount
  name: ansible
  namespace: default
roleRef:
  kind: ClusterRole
  name: ansible
  apiGroup: rbac.authorization.k8s.io