apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansible
rules:
  - apiGroups:
      - ""
    resources: 
      - namespaces
      - configmaps
      - secrets
      - services
    verbs:
      - get
      - create
      - patch
  - apiGroups:
      - apps
    resources: 
      - deployments
    verbs:
      - get
      - create
      - patch
  - apiGroups:
      - traefik.containo.us
    resources: 
      - ingressroutes
      - middlewares
    verbs:
      - get
      - create
      - patch
  - apiGroups:
      - monitoring.coreos.com
    resources: 
      - podmonitors
    verbs:
      - get
      - create
      - patch
