apiVersion: v1
kind: Config
clusters:
  - name: cluster
    cluster:
      server: https://{{ host }}:6443
      certificate-authority-data: {{ certificate_authority_data }}
      insecure-skip-tls-verify: false
users:
  - name: cluster
    user:
      client-certificate-data: {{ client_certificate_data }}
      client-key-data: {{ client_key_data }}
contexts:
  - name: cluster
    context:
      cluster: cluster
      name: cluster
      user: cluster
preferences: {}
current-context: cluster
