[build]
  builder = "paketobuildpacks/builder:base"

[[build.buildpacks]]
  uri = "paketo-buildpacks/web-servers"

[[build.env]]
  name="BP_NODE_RUN_SCRIPTS"
  value="build"

[[build.env]]
  name="BP_WEB_SERVER_ROOT"
  value="dist"

[[build.env]]
  name = "BPE_PORT"
  value = "80"

[[build.env]]
  name = "BP_INCLUDE_FILES"
  value = "nginx.conf:dist"

[[build.env]]
  name="BP_WEB_SERVER"
  value="nginx"
