[build]
  builder = "paketobuildpacks/builder:base"
  include = [
    "dist"
  ]

[[build.buildpacks]]
  uri = "paketo-buildpacks/web-servers"

[[ build.env ]]
  name="BP_NODE_RUN_SCRIPTS"
  value="build"

[[ build.env ]]
  name="BP_WEB_SERVER_ROOT"
  value="dist"

[[build.env]]
  name = "BPE_PORT"
  value = "80"
