- name: Create k8s namespace
  kubernetes.core.k8s:
    state: present
    kind: namespace
    name: "{{ k8s_namespace }}"
- name: Add kubernetes resources
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('ansible.builtin.template', item) }}"
    wait: true
    wait_timeout: 300
  with_items:
    - deployment.yaml
    - service.yaml
