- name: Install iptables service
  become: true
  ansible.builtin.apt:
    name: iptables-persistent
    state: present
- name: Remove persisted rules v4
  become: true
  ansible.builtin.file:
    path: /etc/iptables/rules.v4
    state: absent
- name: Remove persisted rules v6
  become: true
  ansible.builtin.file:
    path: /etc/iptables/rules.v6
    state: absent
- name: Setup iptables v4
  ansible.builtin.include_tasks: iptables_rules.yaml
  vars:
    ip_version: ipv4
- name: Setup iptables v6
  ansible.builtin.include_tasks: iptables_rules.yaml
  vars:
    ip_version: ipv6
- name: Setup iptables v4 Cloudflare rules
  ansible.builtin.include_tasks: iptables_cloudflare_rules.yaml
  vars:
    ip_version: ipv4
- name: Setup iptables v6 Cloudflare rules
  ansible.builtin.include_tasks: iptables_cloudflare_rules.yaml
  vars:
    ip_version: ipv6
- name: Save iptables v4
  become: true
  ansible.builtin.shell:
    cmd: iptables-save > /etc/iptables/rules.v4
- name: Save iptables v6
  become: true
  ansible.builtin.shell:
    cmd: ip6tables-save > /etc/iptables/rules.v6
- name: Restart iptables services
  become: true
  ansible.builtin.service:
    name: netfilter-persistent.service
    enabled: true
    state: restarted