- name: Change root password
  become: true
  ansible.builtin.user:
    name: root
    state: present
    password: "{{ new_root_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
  vars:
    new_root_password: "{{ lookup('ansible.builtin.password', '/dev/null', seed='{{ inventory_hostname }}-root-password') }}"