- name: Disable incomming traffic by default
  become: true
  community.general.ufw:
    default: deny
    direction: incoming
  notify: Restart UFW
- name: Enable outgoing traffic by default
  become: true
  community.general.ufw:
    default: allow
    direction: outgoing
  notify: Restart UFW
- name: Enable SSH port
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp
    comment: SSH
  notify: Restart UFW
- name: Enable Kubernetes port
  become: true
  community.general.ufw:
    rule: allow
    port: "6443"
    proto: tcp
    comment: Kubernetes
  notify: Restart UFW
