- name: Deploy Kubernetes demo
  hosts: cluster
  gather_facts: false
  vars_files:
    - ../vars/vault.yaml
    - ../vars/defaults.yaml
  tasks:
    - name: Deploy db
      ansible.builtin.include_role:
        name: deploy_postgres_db
      vars:
        k8s_name: "{{ db_host }}"
        host_prefix: demo
        db_backup_exclude_tables: []
    - name: Deploy token handler
      ansible.builtin.include_role:
        name: deploy_token_handler
      vars:
        host_prefix: demo
        client_id: "{{ api_client_id }}"
        client_secret: "{{ api_client_secret }}"
        identity_provider_base_path: https://auth.{{ hostname }}
    - name: Deploy webdriver
      ansible.builtin.include_role:
        name: deploy_webdriver
    - name: Deploy server
      ansible.builtin.include_role:
        name: deploy_spring_app
      vars:
        image: mucsi96/kubetools-demo-app-server
        tag_prefix: demo-app-server
        host_prefix: demo
        base_path: /api
        app_env:
          POSTGRES_DB: "{{ db_name }}"
          POSTGRES_HOSTNAME: "{{ db_host }}"
          POSTGRES_PORT: "{{ db_port }}"
          POSTGRES_USER: "{{ db_username }}"
          POSTGRES_PASSWORD: "{{ db_password }}"
          MESSAGE: Hello from kubetools demo!
    - name: Deploy client
      ansible.builtin.include_role:
        name: deploy_client_app
      vars:
        image: mucsi96/kubetools-demo-app-client
        tag_prefix: demo-app-client
        host_prefix: demo
