- name: Enable root login
  hosts: cluster
  gather_facts: false
  roles:
    - role: enable_root_login
      vars:
        root_password: "123"
        ansible_user: vagrant
        ansible_ssh_pass: vagrant
        ansible_port: 22
