name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: any
  cancel-in-progress: true

jobs:
  test-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo_app/server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - run: mvn test -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

  test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo_app/client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: demo_app/client/yarn.lock
      - run: yarn --frozen-lockfile
      - run: yarn test:ci

  build-python-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python scripts/build_python_lib.py ${{ secrets.GITHUB_TOKEN }}

  build-server-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Ansible Vault key
        run: |
          mkdir .ansible
          echo "${{ secrets.ANSIBLE_VAULT_KEY }}" > .ansible/vault_key
          
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - run: pip install -r requirements.txt
      - run: python scripts/build_server_lib.py ${{ secrets.GITHUB_TOKEN }}

  build-ansible-collection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python scripts/build_ansible_collection.py ${{ secrets.GITHUB_TOKEN }}

  build-images:
    runs-on: ubuntu-latest
    needs:
      - test-server
      - test-client
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Ansible Vault key
        run: |
          mkdir .ansible
          echo "${{ secrets.ANSIBLE_VAULT_KEY }}" > .ansible/vault_key

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt

      - uses: buildpacks/github-actions/setup-pack@v5.1.0
      - run: python scripts/build_images.py ${{ secrets.GITHUB_TOKEN }}

  e2e-test:
    runs-on: macos-12
    needs: build-images
    steps:
      - uses: actions/checkout@v3

      - name: Get Ansible Vault key
        run: |
          mkdir .ansible
          echo "${{ secrets.ANSIBLE_VAULT_KEY }}" > .ansible/vault_key

      - name: Install sshpass # https://sourceforge.net/projects/sshpass/files/sshpass/
        run: |
          curl --location --output sshpass.tar.gz https://sourceforge.net/projects/sshpass/files/sshpass/1.09/sshpass-1.09.tar.gz
          tar --extract --verbose --gzip --file sshpass.tar.gz
          cd sshpass-*/
          ./configure
          sudo make install

      - name: Install Python requirements
        run: pip3 install -r requirements.txt

      - name: Show Ansible version
        run: ansible --version

      - name: Show Vagrant version
        run: vagrant --version

      - name: Run vagrant up
        run: vagrant up

      - name: Provision
        run: |
          ansible-playbook \
                --extra-vars "subdomain=kubetools-ci tunnel_name=kubetools-ci" \
                playbooks/enable_root_login.yaml \
                playbooks/new_ssh_user.yaml \
                playbooks/ssh_hardening.yaml \
                playbooks/update_packages.yaml \
                playbooks/install_kubernetes.yaml \
                playbooks/deploy_kubernetes_sso_portal.yaml \
                playbooks/deploy_cloudflare_tunnel.yaml \
                playbooks/deploy_kubernetes_monitoring.yaml \
                playbooks/deploy_kubernetes_demo.yaml

      - name: Test
        env:
          SUBDOMAIN: kubetools-ci
        run: pytest --junitxml=junit/test-results.xml
      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: Test Report
          path: |
            reports
            junit/test-results.xml
