---
argument_specs:
  main:
    options:
      hostname:
        type: str
        required: true
      auth_middelware_name:
        type: str
        required: true
      sso_users:
        type: list
        required: true
        elements: dict
        options:
          username:
            type: str
            required: true
          password:
            type: str
            required: true
          roles:
            type: list
            elements: str
            required: true
          display_name:
            type: str
            required: true
          email:
            type: str
            required: true
